Модели, дао-слой и сервис-слой для SERVICE_REQUEST и EQUIPMENT_ORDER
Semyon-Fomichyov/students_service_center_crm pull request #4
Opened 2021-04-02 13:53 UTC by EsReich

2021-04-03 10:13 UTC, Semyon-Fomichyov requested changes

2021-04-03 10:13 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/model/ServiceRequest.java
> +    @Column(name = "problem")
Нам точно нужны все эти аннотация Column?

2021-04-03 10:13 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/model/ServiceRequest.java
> +        }
Может вместо проверки, инициализацию сразу в строке объявления сделать?

2021-04-03 10:13 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/repository/EquipmentOrderRepositoryImpl.java
> +    }
А нам точно нужны аннотации Autowired и PersistentContext одновременно?

2021-04-03 10:13 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/service/EquipmentOrderServiceImpl.java
> +    @Transactional
Если аннотация висит над всеми метода, её можно повесить над классом.

2021-04-03 10:13 UTC, Semyon-Fomichyov commented on src/main/resources/tables.sql
> +                  );
SQL скрипт нам не нужен, если за нас создает таблицы хибернейт.

2021-04-05 15:17 UTC, Semyon-Fomichyov approved these changes

2021-04-05 15:31 UTC, ZloyGremlinJE approved these changes

2021-04-06 07:35 UTC, merged