Добавил сущности Client и ClientEmployee. DAO слой и сервисный слой. …
Semyon-Fomichyov/students_service_center_crm pull request #7
Opened 2021-04-03 03:34 UTC by vladeg1977

…Таблицы создаются, связь учитывается

2021-04-03 10:35 UTC, Semyon-Fomichyov requested changes

2021-04-03 10:35 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/model/ClientEmployee.java
> +}
Попробуй создай клиента, несколько сотрудников, свяжи их, сохрани в базу, потом достань и выведи через туСтринг или сравни через equals друг с другом, все ли отработает корректно.

2021-04-03 10:35 UTC, Semyon-Fomichyov commented on src/main/java/com/jm/students/service/ClientServiceImpl.java
> +    @Override
Над методами которые только читают данные, можно использовать аннотацию Transactional с ключом readOnly = true

2021-04-05 11:13 UTC, vladeg1977 commented on src/main/java/com/jm/students/service/ClientServiceImpl.java
> +    @Override
Переделал

2021-04-05 11:16 UTC, vladeg1977 commented on src/main/java/com/jm/students/model/ClientEmployee.java
> +}
Проблема была stackoverflowerror. Связано было с аннотациями Lombok из-за связи OneToMany. Исправил

2021-04-07 15:46 UTC, closed without merging